name: rasterenv
channels:
- defaults
- <develop>
- conda-forge
dependencies:
- affine=2.3.*
- appdirs=1.4.*
- asn1crypto=0.24.*
- attrs=21.4.*
- backcall=0.2.*
- backports=1.0
- backports.functools_lru_cache=1.6.*
- blas=2.112
- blas-devel=3.9.*
- bleach=5.0.*
- bokeh=1.2.*
- boost-cpp=1.74.*
- botocore=1.15.*
- bottleneck=1.2.*
- brotlipy=0.7.*
- bzip2=1.0.*
- ca-certificates=2022.6.*
- cartopy=0.17.*
- certifi=2021.5.*
- cffi=1.14.*
- cfitsio=3.430
- cftime=1.1.*
- chardet=3.0.*
- charset-normalizer=2.1.*
- click-plugins=1.1.*
- cligj=0.7.*
- cloudpickle=2.1.*
- colorama=0.4.*
- colorcet=3.0.*
- cryptography=35.0.*
- curl=7.68.*
- cycler=0.11.*
- cython=0.29.*
- cytoolz=0.10.*
- dask=1.2.*
- dask-core=1.2.*
- datashader=0.7.*
- datashape=0.5.*
- decorator=5.1.*
- defusedxml=0.7.*
- descartes=1.1.*
- distributed=1.28.*
- driveanon=0.1.*
- entrypoints=0.4
- expat=2.2.*
- fiona=1.8.*
- freetype=2.10.*
- freexl=1.0.*
- gdal=2.3.*
- geojson=2.5.*
- geopandas=0.6.*
- geos=3.7.*
- geotiff=1.4.*
- geoviews=1.6.*
- geoviews-core=1.6.*
- gettext=0.19.*
- glib=2.72.*
- glib-tools=2.72.*
- h5py=2.9.*
- hdf4=4.2.*
- hdf5=1.10.*
- heapdict=1.0.*
- holoviews=1.12.*
- icc_rt=2019.0.*
- icu=68.2
- idna=3.3
- imageio=2.8.*
- importlib-metadata=4.2.*
- importlib_metadata=1.6.*
- intel-openmp=2022.1.*
- ipykernel=5.2.*
- ipython=7.13.*
- ipython_genutils=0.2.*
- ipywidgets=7.7.*
- isodate=0.6.*
- jedi=0.16.*
- jinja2=2.11.*
- jmespath=0.10.*
- joblib=1.1.*
- jpeg=9e
- jsonschema=3.2.*
- jupyter=1.0.*
- jupyter_client=7.0.*
- jupyter_console=6.4.*
- jupyter_core=4.6.*
- jupyterlab_widgets=1.1.*
- kealib=1.4.*
- kiwisolver=1.2.*
- krb5=1.16.*
- lerc=3.0
- libblas=3.9.*
- libcblas=3.9.*
- libclang=11.1.*
- libcurl=7.68.*
- libdeflate=1.12
- libffi=3.4.*
- libgdal=2.3.*
- libglib=2.72.*
- libiconv=1.16
- libkml=1.3.*
- liblapack=3.9.*
- liblapacke=3.9.*
- libnetcdf=4.6.*
- libpng=1.6.*
- libpq=11.5
- libsodium=1.0.*
- libspatialindex=1.9.*
- libspatialite=4.3.*
- libssh2=1.8.*
- libtiff=4.4.*
- libxml2=2.9.*
- libxslt=1.1.*
- libzlib=1.2.*
- llvmlite=0.31.*
- locket=1.0.*
- lxml=4.6.*
- lz4-c=1.9.*
- m2w64-expat=2.1.*
- m2w64-gcc-libgfortran=5.3.*
- m2w64-gcc-libs=5.3.*
- m2w64-gcc-libs-core=5.3.*
- m2w64-gettext=0.19.*
- m2w64-gmp=6.1.*
- m2w64-libiconv=1.14
- m2w64-libwinpthread-git=5.0.*
- m2w64-xz=5.2.*
- mapclassify=2.0.*
- markdown=2.6.*
- markupsafe=1.1.*
- matplotlib=3.1.*
- matplotlib-base=3.1.*
- mistune=0.8.*
- mkl=2022.1.*
- mkl-devel=2021.4.*
- mkl-include=2021.4.*
- mkl-service=2.4.*
- msgpack-python=0.6.*
- msys2-conda-epoch=20160418
- multipledispatch=0.6.*
- munch=2.5.*
- nbconvert=5.6.*
- nbformat=5.1.*
- nest-asyncio=1.5.*
- netcdf4=1.5.*
- networkx=2.4
- notebook=6.0.*
- numba=0.48.*
- numpy=1.19.*
- olefile=0.46
- openjpeg=2.3.*
- openssl=1.1.*
- owslib=0.19.*
- packaging=21.3
- pandas=1.0.*
- pandoc=2.9.*
- pandocfilters=1.5.*
- panel=0.6.*
- param=1.12.*
- parso=0.8.*
- partd=1.2.*
- patsy=0.5.*
- pcre=8.45
- pickleshare=0.7.*
- pillow=7.1.*
- pip=19.1.*
- poppler=0.67.*
- poppler-data=0.4.*
- postgresql=11.5
- proj4=5.2.*
- prometheus_client=0.14.*
- prompt-toolkit=3.0.*
- prompt_toolkit=3.0.*
- psutil=5.7.*
- pycparser=2.21
- pyct=0.4.*
- pyct-core=0.4.*
- pyepsg=0.4.*
- pygments=2.12.*
- pykdtree=1.3.*
- pyopenssl=22.0.*
- pyorbital=1.5.*
- pyparsing=3.0.*
- pyqt=5.12.*
- pyreadline=2.1
- pyresample=1.15.*
- pyrsistent=0.16.*
- pyshp=2.3.*
- pysocks=1.7.*
- pyspectral=0.9.*
- python=3.6.*
- python-dateutil=2.8.*
- python-geotiepoints=1.1.*
- python_abi=3.6
- pytz=2022.1
- pyviz_comms=2.2.*
- pywavelets=1.1.*
- pywin32=227
- pywinpty=0.5.*
- pyyaml=5.4.*
- pyzmq=19.0.*
- qt=5.12.*
- qtconsole=4.7.*
- qtpy=1.9.*
- rasterio=1.0.*
- requests=2.28.*
- rioxarray=0.0.*
- rtree=0.9.*
- s3transfer=0.3.*
- satpy=0.16.*
- scikit-image=0.16.*
- scikit-learn=0.22.*
- seaborn=0.10.*
- seaborn-base=0.10.*
- send2trash=1.8.*
- setuptools=49.6.*
- shapely=1.6.*
- sip=4.19.*
- six=1.16.*
- snuggs=1.4.*
- sortedcontainers=2.4.*
- sqlite=3.39.*
- statsmodels=0.11.*
- suds-jurko=0.6
- tbb=2021.5.*
- tblib=1.7.*
- terminado=0.8.*
- testpath=0.3.*
- tk=8.6.*
- toolz=0.12.*
- tornado=6.0.*
- tqdm=4.64.*
- traitlets=4.3.*
- trollimage=1.12.*
- trollsift=0.4.*
- typing_extensions=3.10.*
- ucrt=10.0.*
- ulmo=0.8.*
- vc=14.2
- vs2015_runtime=14.29.*
- wcwidth=0.2.*
- webencodings=0.5.*
- wheel=0.37.*
- widgetsnbextension=3.6.*
- win_inet_pton=1.1.*
- wincertstore=0.2
- winpty=0.4.*
- xarray=0.15.*
- xerces-c=3.2.*
- xz=5.2.*
- yaml=0.2.*
- zeromq=4.3.*
- zict=2.0.*
- zipp=3.1.*
- zlib=1.2.*
- zstd=1.5.*
- pip:
  - beautifulsoup4==4.9.*
  - boto3==1.9.*
  - bs4==0.0.*
  - click==6.7
  - configobj==5.0.*
  - docutils==0.14
  - elevation==1.0.*
  - fasteners==0.15
  - future==0.17.*
  - geotext==0.3.*
  - goespy==0.2.*
  - mat73==0.50
  - matplotlib-scalebar==0.6.*
  - monotonic==1.5
  - pathlib==1.0.*
  - pygeoprocessing==1.6.*
  - pygeotools==0.6.*
  - pyproj==3.0.*
  - pyqt5-sip==4.19.*
  - pyqtchart==5.12
  - pyqtwebengine==5.12.*
  - pysolar==0.10
  - scipy==1.3.*
  - soupsieve==2.0
  - tartes==1.4
  - urllib3==1.24.*
